from openpyxl import load_workbook
from openpyxl.styles import Font, Border, Side
from io import BytesIO
import pandas as pd

"""
populate_syscad_inputs_rev1.py

This module populates the 'SysCAD Inputs' category in a master equipment datasheet
based on a compact SysCAD streamtable Excel file. Each sheet in the streamtable represents
an equipment type with one or more unit tags and associated parameter values.

Main Features:
- Reads the master datasheet generated by automation_test1.
- Identifies matching equipment sheets in the streamtable.
- For each parameter in the 'SysCAD Inputs' category:
    - Matches it to a parameter tag in the streamtable using a defined mapping.
    - Copies parameter values into the corresponding row for each unit.
    - Inserts equipment tags (unit names) as column headers in row 3.
    - Bold formats the equipment tags and applies borders to all inserted cells.
    - Rounds values to two decimal places if they are floats.
    - Replaces the master datasheet units with the ones in the streamtable if they differ.

Returns:
- A BytesIO stream of the updated Excel file
- A list of equipment types present in the master sheet but missing in the streamtable

Author: Asfiya Khanam
Created: June 2025
"""

def populate_syscad_inputs(master_file: BytesIO, streamtable_file: BytesIO) -> BytesIO:
    # Load workbooks
    master_wb = load_workbook(master_file)
    streamtable_wb = load_workbook(streamtable_file, data_only=True)

    # Styling
    thin_border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )

    # Track equipment types
    master_sheets = set(master_wb.sheetnames)
    stream_sheets = set(streamtable_wb.sheetnames)
    common_sheets = master_sheets.intersection(stream_sheets)
    missing_sheets = list(master_sheets - stream_sheets)

    for equipment_type in common_sheets:
        master_sheet = master_wb[equipment_type]
        stream_sheet = streamtable_wb[equipment_type]

        # Parameter mapping: master label -> streamtable tag
        parameter_mapping = {
            "Operating Temperature": "Prod.T (C)",
            "Operating Density": "Prod.Rho (kg/m^3)",
            "Design Density": "Prod.Rho (kg/m^3)",
            "Operating Slurry pH": "Prod.pH",
            "Design Slurry pH": "Prod.pH",
            "Flow Rate to/from Vessel": "Prod.Qm (kg/h)"
        }

        # Get unit tags from streamtable (row 1, col D onward)
        stream_unit_tags = [cell.value for cell in stream_sheet[1][3:] if cell.value]

        # Populate unit tags into master sheet row 3 (D3 onward), bolded
        for i, tag in enumerate(stream_unit_tags):
            cell = master_sheet.cell(row=3, column=4 + i, value=tag)
            cell.font = Font(bold=True)
            cell.border = thin_border

        # Map streamtag → row number
        stream_tag_to_row = {
            row[2].value.strip(): row_idx
            for row_idx, row in enumerate(stream_sheet.iter_rows(min_row=3, max_col=3), start=3)
            if row[2].value
        }

        # Get parameters from master sheet: row mapping for each parameter
        param_rows = {}
        syscad_start = None
        for row in range(1, master_sheet.max_row + 1):
            cat_val = master_sheet.cell(row=row, column=1).value
            if cat_val and "SysCAD Inputs" in str(cat_val):
                syscad_start = row + 1
                continue
            if syscad_start and row >= syscad_start:
                val = master_sheet.cell(row=row, column=1).value
                if val and "Engineering Inputs" in str(val):
                    break
                param_name = master_sheet.cell(row=row, column=2).value
                if param_name:
                    param_rows[param_name.strip()] = row

        # Re-fetch master unit tags now that we've populated them
        master_unit_tags = [cell.value for cell in master_sheet[3][3:] if cell.value]

        # Populate values and update units
        for col_offset, unit_tag in enumerate(master_unit_tags):
            if unit_tag not in stream_unit_tags:
                continue
            stream_col = stream_unit_tags.index(unit_tag) + 4  # D=4 in Excel
            for master_param, stream_tag in parameter_mapping.items():
                if master_param not in param_rows or stream_tag not in stream_tag_to_row:
                    continue
                master_row = param_rows[master_param]
                stream_row = stream_tag_to_row[stream_tag]

                value = stream_sheet.cell(row=stream_row, column=stream_col).value
                if value is not None:
                    master_col = col_offset + 4  # D=4
                    cell = master_sheet.cell(row=master_row, column=master_col, value=round(value, 2) if isinstance(value, float) else value)
                    cell.border = thin_border

                # Update unit in master sheet (column C)
                stream_unit = stream_sheet.cell(row=stream_row, column=2).value  # Column B
                master_unit = master_sheet.cell(row=master_row, column=3).value  # Column C
                if stream_unit and master_unit != stream_unit:
                    unit_cell = master_sheet.cell(row=master_row, column=3, value=stream_unit)
                    unit_cell.border = thin_border

    # Save result to BytesIO
    output_stream = BytesIO()
    master_wb.save(output_stream)
    output_stream.seek(0)
    return output_stream, missing_sheets
